[project]
name = "medida-enterprise-api-example"
version = "0.1.0"
readme = "readme.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
]

[dependency-groups]
dev = [
    "pynvim>=0.5.2",
    "pyright>=1.1.403",
    "ruff>=0.12.7",
]
